-- =====================================================
-- AGENTS
-- =====================================================

INSERT INTO agents (
    id,
    full_name,
    email,
    bank_name,
    account_number,
    branch_code,
    is_active,
    created_by,
    created_at,
    updated_at
) VALUES
      (
          RANDOM_UUID(),
          'Sarah Jacobs',
          'sarah.jacobs@propcoza.co.za',
          'FNB',
          '62145897321',
          '250655',
          TRUE,
          'system',
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
      ),
      (
          RANDOM_UUID(),
          'Michael Petersen',
          'michael.petersen@propcoza.co.za',
          'Standard Bank',
          '45879632145',
          '051001',
          TRUE,
          'system',
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
      ),
      (
          RANDOM_UUID(),
          'Ayesha Khan',
          'ayesha.khan@propcoza.co.za',
          'Absa',
          '78541236987',
          '632005',
          TRUE,
          'system',
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
      ),
      (
          RANDOM_UUID(),
          'Daniel Rossouw',
          'daniel.rossouw@propcoza.co.za',
          'Nedbank',
          '96325874125',
          '198765',
          TRUE,
          'system',
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
      ),
      (
          RANDOM_UUID(),
          'Fatima Daniels',
          'fatima.daniels@propcoza.co.za',
          'Capitec',
          '14785236901',
          '470010',
          TRUE,
          'system',
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
      );

-- =====================================================
-- RENTALS
-- NOTE:
-- We use subqueries to fetch agent UUIDs by email
-- because IDs are UUIDs generated via RANDOM_UUID()
-- =====================================================

INSERT INTO rentals (
    id,
    agent_id,
    address,
    tenant_name,
    payment_date,
    start_date,
    end_date,
    auto_renew,
    status,
    landlord_name,
    landlord_bank_name,
    landlord_acc_no,
    landlord_branch,
    base_rent,
    rental_commision_percent,
    office_split,
    agent_split,
    agent_paye,
    vat_registered,
    created_by,
    created_at,
    updated_at
)
VALUES

-- Sarah (3 rentals)

(
    RANDOM_UUID(),
    (SELECT id FROM agents WHERE email = 'sarah.jacobs@propcoza.co.za'),
    '12 Beach Road, Sea Point, Cape Town',
    'John Smith',
    DATE '2026-04-01',
    DATE '2026-04-01',
    NULL,
    TRUE,
    'ACTIVE',
    'Amanda Naidoo',
    'FNB',
    '55874123698',
    '250655',
    18500.00,
    0.10,
    0.30,
    0.70,
    0.18,
    TRUE,
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

(
    RANDOM_UUID(),
    (SELECT id FROM agents WHERE email = 'sarah.jacobs@propcoza.co.za'),
    '44 Kloof Street, Gardens, Cape Town',
    'Emma Brown',
    DATE '2026-04-05',
    DATE '2026-04-05',
    NULL,
    TRUE,
    'ACTIVE',
    'Chris Hendricks',
    'Absa',
    '44789632145',
    '632005',
    14200.00,
    0.10,
    0.30,
    0.70,
    0.18,
    TRUE,
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

(
    RANDOM_UUID(),
    (SELECT id FROM agents WHERE email = 'sarah.jacobs@propcoza.co.za'),
    '7 Main Road, Green Point, Cape Town',
    'Luke Adams',
    DATE '2026-04-10',
    DATE '2026-04-10',
    NULL,
    TRUE,
    'ACTIVE',
    'Vanessa Jacobs',
    'Standard Bank',
    '78965412301',
    '051001',
    21000.00,
    0.12,
    0.35,
    0.65,
    0.18,
    TRUE,
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Michael (2 rentals)

(
    RANDOM_UUID(),
    (SELECT id FROM agents WHERE email = 'michael.petersen@propcoza.co.za'),
    '18 Oak Avenue, Durbanville',
    'Sophia Miller',
    DATE '2026-04-03',
    DATE '2026-04-03',
    NULL,
    TRUE,
    'ACTIVE',
    'Greg Foster',
    'Nedbank',
    '32165498745',
    '198765',
    16500.00,
    0.10,
    0.30,
    0.70,
    0.18,
    FALSE,
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

(
    RANDOM_UUID(),
    (SELECT id FROM agents WHERE email = 'michael.petersen@propcoza.co.za'),
    '92 Pine Crescent, Bellville',
    'Nathan White',
    DATE '2026-04-08',
    DATE '2026-04-08',
    NULL,
    TRUE,
    'ACTIVE',
    'Tanya Lewis',
    'Capitec',
    '74125896300',
    '470010',
    13200.00,
    0.10,
    0.25,
    0.75,
    0.18,
    TRUE,
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Ayesha (2 rentals)

(
    RANDOM_UUID(),
    (SELECT id FROM agents WHERE email = 'ayesha.khan@propcoza.co.za'),
    '30 Church Street, Stellenbosch',
    'Mia Johnson',
    DATE '2026-04-02',
    DATE '2026-04-02',
    NULL,
    TRUE,
    'ACTIVE',
    'Hassan Patel',
    'FNB',
    '96374125800',
    '250655',
    15500.00,
    0.11,
    0.30,
    0.70,
    0.18,
    TRUE,
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

(
    RANDOM_UUID(),
    (SELECT id FROM agents WHERE email = 'ayesha.khan@propcoza.co.za'),
    '11 Andringa Street, Stellenbosch',
    'Olivia Green',
    DATE '2026-04-12',
    DATE '2026-04-12',
    NULL,
    TRUE,
    'ACTIVE',
    'Jacques Nel',
    'Standard Bank',
    '85236974100',
    '051001',
    17800.00,
    0.10,
    0.30,
    0.70,
    0.18,
    TRUE,
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Daniel (2 rentals)

(
    RANDOM_UUID(),
    (SELECT id FROM agents WHERE email = 'daniel.rossouw@propcoza.co.za'),
    '5 Long Street, CBD, Cape Town',
    'Ethan Hall',
    DATE '2026-04-06',
    DATE '2026-04-06',
    NULL,
    TRUE,
    'ACTIVE',
    'Rebecca Stone',
    'Absa',
    '14725836900',
    '632005',
    19800.00,
    0.10,
    0.30,
    0.70,
    0.18,
    FALSE,
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

(
    RANDOM_UUID(),
    (SELECT id FROM agents WHERE email = 'daniel.rossouw@propcoza.co.za'),
    '73 Loop Street, CBD, Cape Town',
    'Grace Carter',
    DATE '2026-04-15',
    DATE '2026-04-15',
    NULL,
    TRUE,
    'ACTIVE',
    'Simon Williams',
    'Nedbank',
    '65498732100',
    '198765',
    14900.00,
    0.10,
    0.30,
    0.70,
    0.18,
    TRUE,
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Fatima (1 rental)

(
    RANDOM_UUID(),
    (SELECT id FROM agents WHERE email = 'fatima.daniels@propcoza.co.za'),
    '27 Blaauwberg Road, Table View',
    'Noah Turner',
    DATE '2026-04-09',
    DATE '2026-04-09',
    NULL,
    TRUE,
    'ACTIVE',
    'Lauren Adams',
    'Capitec',
    '25836914700',
    '470010',
    17100.00,
    0.10,
    0.30,
    0.70,
    0.18,
    TRUE,
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);