package com.propcoza.legends.tools.rental_transaction_manager.dto;

import jakarta.validation.constraints.AssertTrue;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.FutureOrPresent;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;

/**
 * DTO used when creating a new Rental.
 *
 * The Agent relationship is flattened to its FK (agentId) rather than
 * embedding the full Agent object. The service layer is responsible for
 * resolving the UUID to an Agent entity before persisting.
 *
 * Fields intentionally omitted:
 *   - id            (generated by the database)
 *   - agentGrossComm (derived: companyComm + agentNettComm)
 *   - startDate     (defaults to paymentDate in the entity)
 *   - endDate       (set by the last RentalInstance payment)
 *   - autoRenew     (defaults to true)
 *   - status        (defaults to ACTIVE)
 *   - createdBy     (populated from the security context in the service)
 *   - createdAt     (set by @CreationTimestamp)
 *   - updatedAt     (set by @UpdateTimestamp)
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RentalCreateDto {

    // ------------------------------------------------------------------
    //  Agent (FK — flattened)
    // ------------------------------------------------------------------

    /**
     * The ID of the Agent responsible for this rental.
     * The service layer resolves this to a managed Agent entity.
     */
    @NotNull(message = "Agent ID is required")
    private UUID agentId;

    // ------------------------------------------------------------------
    //  Property
    // ------------------------------------------------------------------

    @NotBlank(message = "Address is required")
    @Size(max = 1000, message = "Address must not exceed 1000 characters")
    private String address;

    @Size(max = 255, message = "Tenant name must not exceed 255 characters")
    private String tenantName;

    // ------------------------------------------------------------------
    //  Scheduling
    // ------------------------------------------------------------------

    @NotNull(message = "Payment date is required")
    @FutureOrPresent(message = "Payment date must be today or in the future")
    private LocalDate paymentDate;

    // ------------------------------------------------------------------
    //  Financial
    // ------------------------------------------------------------------

    @NotNull(message = "Total rent received is required")
    @DecimalMin(value = "0.00", message = "Total rent received cannot be negative")
    private BigDecimal totalRentReceived;

    @NotBlank(message = "Landlord name is required")
    @Size(max = 255, message = "Landlord name must not exceed 255 characters")
    private String landlordName;

    @NotBlank(message = "Landlord bank name is required")
    @Size(max = 100, message = "Landlord bank name must not exceed 100 characters")
    private String landlordBankName;

    /**
     * South African bank account numbers are typically 9–11 digits.
     * Adjust the pattern to match your specific bank's format requirements.
     */
    @NotBlank(message = "Landlord account number is required")
    @Pattern(
            regexp = "^[0-9]{9,11}$",
            message = "Landlord account number must be 9–11 digits"
    )
    private String landlordAccNo;

    @NotBlank(message = "Landlord branch code is required")
    @Size(max = 100, message = "Landlord branch must not exceed 100 characters")
    private String landlordBranch;

    @NotNull(message = "Company commission is required")
    @DecimalMin(value = "0.00", message = "Company commission cannot be negative")
    private BigDecimal companyComm;

    @NotNull(message = "PAYE amount is required")
    @DecimalMin(value = "0.00", message = "PAYE amount cannot be negative")
    private BigDecimal payeAmount;

    @NotNull(message = "Agent nett commission is required")
    @DecimalMin(value = "0.00", message = "Agent nett commission cannot be negative")
    private BigDecimal agentNettComm;

    @NotNull(message = "Landlord pay amount is required")
    @DecimalMin(value = "0.00", message = "Landlord pay amount cannot be negative")
    private BigDecimal landlordPayAmount;

    // ------------------------------------------------------------------
    //  Cross-field validation — mirrors the entity constraint
    // ------------------------------------------------------------------

    /**
     * Ensures agentGrossComm (companyComm + agentNettComm) is internally
     * consistent: gross − paye == nett.
     *
     * Note: agentGrossComm is intentionally excluded from this DTO because
     * it is derived (companyComm + agentNettComm). The service layer should
     * compute and set it before persisting the entity.
     */
    @AssertTrue(message = "Commission values are inconsistent: companyComm + agentNettComm − payeAmount must equal agentNettComm (i.e. payeAmount must equal companyComm)")
    public boolean isCommissionValid() {
        if (companyComm == null || payeAmount == null || agentNettComm == null) {
            return true; // individual @NotNull constraints handle the null case
        }
        // gross = companyComm + agentNettComm
        BigDecimal gross = companyComm.add(agentNettComm);
        return gross.subtract(payeAmount).compareTo(agentNettComm) == 0;
    }
}