spring.application.name=rental-transaction-manager

# H2 Configuration
spring.datasource.url=jdbc:h2:mem:rentalsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enables the H2 Console so you can see the data in your browser
spring.h2.console.enabled=true
# Automatically creates the tables based on your @Entity classes
spring.jpa.hibernate.ddl-auto=update